### ISSUE TITLE
Flet UI is malfunctioning

### ISSUE THREAD

**Issue by AnveshMora** [NagarajuGunda/PyAlgoMate#20]
I have created strategies looks like this
`Broker: Zerodha
Underlyings:
  - NSE:NIFTY BANK
  - NSE:NIFTY 50
  - NSE:NIFTY FIN SERVICE
  - NSE:NIFTY MID SELECT

Strategies:
  SuperTrend1:
    Class: SuperTrendV1
    Path: pyalgomate/strategies/SuperTrendV1.py
    Mode: paper
    Args:
      - underlying: NSE:NIFTY BANK

  SuperTrendV2:
    Class: SuperTrendV1
    Path: pyalgomate/strategies/SuperTrendV1.py
    Mode: paper
    Args:
      - underlying: NSE:NIFTY 50
`

Here I'm running a same strategies on two different instruments and as two different stategies.

Even thought one strategy is taking entry the same is reflecting on other ,

below is the Screen recording:

https://github.com/NagarajuGunda/PyAlgoMate/assets/8730299/cb8b4fae-fbc4-47af-b2fa-e0ae22156cea

**Comment by rsnerella** [comment]
Experienced the similar issue, after state=LIVE condition removal in the strategy, issue is resolved. May be you can check the strategy logic.

**Comment by AnveshMora** [comment]
Ya issue resolved!
